// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yygzltmvslchktdrpswe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5Z3psdG12c2xjaGt0ZHJwc3dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzQ4NTQsImV4cCI6MjA2MzY1MDg1NH0.NMzjRnwSS0lhY-rNJArivY2nVETHdZ4WURVd33oaME8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);